### import library

In [3]:
import pandas as pd
import numpy as np

# load data set
df = pd.read_csv(r"D:\1.My Projects for DS\Data Engineer Role\employee_attrition_dataset_.csv")
df

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,1,58,Male,Single,Finance,Manager,5,7332,81,24,...,No,9,48,16,4,1,1,49,3,No
1,2,48,Female,Divorced,HR,Assistant,4,6069,55,18,...,Yes,9,57,10,4,1,1,25,1,No
2,3,34,Female,Married,Marketing,Manager,4,11485,65,6,...,Yes,3,55,1,1,4,3,21,1,Yes
3,4,27,Female,Divorced,HR,Manager,4,18707,28,12,...,No,9,53,2,3,4,1,46,2,No
4,5,40,Male,Married,HR,Analyst,1,16398,92,3,...,No,1,54,11,1,1,1,43,4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,22,Female,Divorced,Marketing,Manager,5,4276,27,17,...,Yes,3,36,3,4,2,3,18,2,No
9996,9997,35,Female,Divorced,Marketing,Executive,3,10327,60,19,...,No,5,59,4,4,3,4,31,1,No
9997,9998,23,Male,Divorced,IT,Manager,3,12592,68,10,...,Yes,4,54,10,4,4,2,12,1,Yes
9998,9999,42,Female,Single,Marketing,Manager,3,9287,26,18,...,Yes,9,51,16,3,2,2,18,3,No
9999,10000,39,Female,Divorced,Finance,Executive,2,7225,54,16,...,Yes,4,51,6,4,1,1,6,2,Yes

In [4]:
# Print first 5 rows to verify data loaded
print("Data Loaded Successfully ✅")
print(df.head())

Data Loaded Successfully ✅
   Employee_ID  Age  Gender Marital_Status Department   Job_Role  Job_Level  \
0            1   58    Male         Single    Finance    Manager          5
1            2   48  Female       Divorced         HR  Assistant          4
2            3   34  Female        Married  Marketing    Manager          4
3            4   27  Female       Divorced         HR    Manager          4
4            5   40    Male        Married         HR    Analyst          1

   Monthly_Income  Hourly_Rate  Years_at_Company  ...  Overtime  \
0            7332           81                24  ...        No
1            6069           55                18  ...       Yes
2           11485           65                 6  ...       Yes
3           18707           28                12  ...        No
4           16398           92                 3  ...        No

   Project_Count  Average_Hours_Worked_Per_Week  Absenteeism  \
0              9                             48           16
1              9                             57           10
2              3                             55            1
3              9                             53            2
4              1                             54           11

   Work_Environment_Satisfaction  Relationship_with_Manager Job_Involvement  \
0                              4                          1               1
1                              4                          1               1
2                              1                          4               3
3                              3                          4               1
4                              1                          1               1

   Distance_From_Home  Number_of_Companies_Worked  Attrition
0                  49                           3         No
1                  25                           1         No
2                  21                           1        Yes
3                  46                           2         No
4                  43                           4         No

[5 rows x 26 columns]

### Basic Info & Check

In [6]:
# -------------------------------
# STEP 2: BASIC DATA CHECK
# -------------------------------

# Check data types and non-null values
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Employee_ID                    10000 non-null  int64
 1   Age                            10000 non-null  int64
 2   Gender                         10000 non-null  object
 3   Marital_Status                 10000 non-null  object
 4   Department                     10000 non-null  object
 5   Job_Role                       10000 non-null  object
 6   Job_Level                      10000 non-null  int64
 7   Monthly_Income                 10000 non-null  int64
 8   Hourly_Rate                    10000 non-null  int64
 9   Years_at_Company               10000 non-null  int64
 10  Years_in_Current_Role          10000 non-null  int64
 11  Years_Since_Last_Promotion     10000 non-null  int64
 12  Work_Life_Balance              10000 non-null  int64
 13  Job_Satisfaction               10000 non-null  int64
 14  Performance_Rating             10000 non-null  int64
 15  Training_Hours_Last_Year       10000 non-null  int64
 16  Overtime                       10000 non-null  object
 17  Project_Count                  10000 non-null  int64
 18  Average_Hours_Worked_Per_Week  10000 non-null  int64
 19  Absenteeism                    10000 non-null  int64
 20  Work_Environment_Satisfaction  10000 non-null  int64
 21  Relationship_with_Manager      10000 non-null  int64
 22  Job_Involvement                10000 non-null  int64
 23  Distance_From_Home             10000 non-null  int64
 24  Number_of_Companies_Worked     10000 non-null  int64
 25  Attrition                      10000 non-null  object
dtypes: int64(20), object(6)
memory usage: 2.0+ MB
None

In [7]:
# Check missing values in each column
print(df.isnull().sum())

Employee_ID                      0
Age                              0
Gender                           0
Marital_Status                   0
Department                       0
Job_Role                         0
Job_Level                        0
Monthly_Income                   0
Hourly_Rate                      0
Years_at_Company                 0
Years_in_Current_Role            0
Years_Since_Last_Promotion       0
Work_Life_Balance                0
Job_Satisfaction                 0
Performance_Rating               0
Training_Hours_Last_Year         0
Overtime                         0
Project_Count                    0
Average_Hours_Worked_Per_Week    0
Absenteeism                      0
Work_Environment_Satisfaction    0
Relationship_with_Manager        0
Job_Involvement                  0
Distance_From_Home               0
Number_of_Companies_Worked       0
Attrition                        0
dtype: int64

In [8]:
# -------------------------------
# STEP 3: DATA CLEANING
# -------------------------------

# Remove duplicate rows
df = df.drop_duplicates()
print("Data Cleaning Done ✅")

Data Cleaning Done ✅

In [9]:
# -------------------------------
# STEP 4: FIX DATA TYPES
# -------------------------------

# Convert Age to integer
df['Age'] = df['Age'].astype(int)

# Convert Monthly Income to float
df['Monthly_Income'] = df['Monthly_Income'].astype(int)

In [10]:
# -------------------------------
# STEP 5: FEATURE ENGINEERING
# -------------------------------

# 1. Create Income Category column
# Low < 5000, Medium 5000–15000, High > 15000
def income_category(income):
    if income < 5000:
        return "Low"
    elif income <= 15000:
        return "Medium"
    else:
        return "High"

In [11]:
# Apply function on Monthly_Income column
df['Income_Category'] = df['Monthly_Income'].apply(income_category)


# 2. Create Experience Level column
# Based on Years_at_Company
def experience_level(years):
    if years < 3:
        return "Junior"
    elif years <= 7:
        return "Mid"
    else:
        return "Senior"

In [12]:
# Apply function
df['Experience_Level'] = df['Years_at_Company'].apply(experience_level)


# 3. Create Promotion Status column
# If employee working >=5 years → No Promotion
def promotion_status(years):
    if years >= 5:
        return "No Promotion 5+ Years"
    else:
        return "Recently Promoted"

# Apply function
df['Promotion_Status'] = df['Years_at_Company'].apply(promotion_status)

In [13]:
df.columns

Index(['Employee_ID', 'Age', 'Gender', 'Marital_Status', 'Department',
       'Job_Role', 'Job_Level', 'Monthly_Income', 'Hourly_Rate',
       'Years_at_Company', 'Years_in_Current_Role',
       'Years_Since_Last_Promotion', 'Work_Life_Balance', 'Job_Satisfaction',
       'Performance_Rating', 'Training_Hours_Last_Year', 'Overtime',
       'Project_Count', 'Average_Hours_Worked_Per_Week', 'Absenteeism',
       'Work_Environment_Satisfaction', 'Relationship_with_Manager',
       'Job_Involvement', 'Distance_From_Home', 'Number_of_Companies_Worked',
       'Attrition', 'Income_Category', 'Experience_Level', 'Promotion_Status'],
      dtype='object')

In [14]:
df['Risk_Flag'] = "Normal"

df.loc[
    (
        (df['Attrition'] == 'Yes') &
        (df['Work_Environment_Satisfaction'] <= 2)
    ) |
    (
        (df['Promotion_Status'] == "No Promotion 5+ Years") &
        (df['Work_Environment_Satisfaction'] <= 2) &
        (df['Job_Involvement'] <= 2)
    ),
    'Risk_Flag'
] = "High Risk"

In [15]:
# -------------------------------
# STEP 6: DATA VALIDATION
# -------------------------------

# Check unique values of new columns (for correctness)
print("Unique Income Categories:", df['Income_Category'].unique())
print("Unique Experience Levels:", df['Experience_Level'].unique())
print("Unique Promotion Status:", df['Promotion_Status'].unique())
print("Unique Risk Flags:", df['Risk_Flag'].unique())

Unique Income Categories: ['Medium' 'High' 'Low']
Unique Experience Levels: ['Senior' 'Mid' 'Junior']
Unique Promotion Status: ['No Promotion 5+ Years' 'Recently Promoted']
Unique Risk Flags: ['Normal' 'High Risk']

In [16]:
c

INFO:root:ETL Process Started

In [17]:
# -------------------------------
# BONUS: ERROR HANDLING
# -------------------------------

# Try to load file safely
try:
    df = pd.read_csv("employee_data.csv")
    logging.info("File Loaded Successfully")
except Exception as e:
    logging.error(f"Error: {e}")

ERROR:root:Error: [Errno 2] No such file or directory: 'employee_data.csv'

In [18]:
df

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition,Income_Category,Experience_Level,Promotion_Status,Risk_Flag
0,1,58,Male,Single,Finance,Manager,5,7332,81,24,...,4,1,1,49,3,No,Medium,Senior,No Promotion 5+ Years,Normal
1,2,48,Female,Divorced,HR,Assistant,4,6069,55,18,...,4,1,1,25,1,No,Medium,Senior,No Promotion 5+ Years,Normal
2,3,34,Female,Married,Marketing,Manager,4,11485,65,6,...,1,4,3,21,1,Yes,Medium,Mid,No Promotion 5+ Years,High Risk
3,4,27,Female,Divorced,HR,Manager,4,18707,28,12,...,3,4,1,46,2,No,High,Senior,No Promotion 5+ Years,Normal
4,5,40,Male,Married,HR,Analyst,1,16398,92,3,...,1,1,1,43,4,No,High,Mid,Recently Promoted,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,22,Female,Divorced,Marketing,Manager,5,4276,27,17,...,4,2,3,18,2,No,Low,Senior,No Promotion 5+ Years,Normal
9996,9997,35,Female,Divorced,Marketing,Executive,3,10327,60,19,...,4,3,4,31,1,No,Medium,Senior,No Promotion 5+ Years,Normal
9997,9998,23,Male,Divorced,IT,Manager,3,12592,68,10,...,4,4,2,12,1,Yes,Medium,Senior,No Promotion 5+ Years,Normal
9998,9999,42,Female,Single,Marketing,Manager,3,9287,26,18,...,3,2,2,18,3,No,Medium,Senior,No Promotion 5+ Years,Normal
9999,10000,39,Female,Divorced,Finance,Executive,2,7225,54,16,...,4,1,1,6,2,Yes,Medium,Senior,No Promotion 5+ Years,Normal

In [19]:
import os
print(os.getcwd())

C:\Users\anshp\Data Engineer

In [20]:
# so my data there is two time column create 1>Experience Level, so we cleand it and fixed it Promotion Status

In [21]:
df

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition,Income_Category,Experience_Level,Promotion_Status,Risk_Flag
0,1,58,Male,Single,Finance,Manager,5,7332,81,24,...,4,1,1,49,3,No,Medium,Senior,No Promotion 5+ Years,Normal
1,2,48,Female,Divorced,HR,Assistant,4,6069,55,18,...,4,1,1,25,1,No,Medium,Senior,No Promotion 5+ Years,Normal
2,3,34,Female,Married,Marketing,Manager,4,11485,65,6,...,1,4,3,21,1,Yes,Medium,Mid,No Promotion 5+ Years,High Risk
3,4,27,Female,Divorced,HR,Manager,4,18707,28,12,...,3,4,1,46,2,No,High,Senior,No Promotion 5+ Years,Normal
4,5,40,Male,Married,HR,Analyst,1,16398,92,3,...,1,1,1,43,4,No,High,Mid,Recently Promoted,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,22,Female,Divorced,Marketing,Manager,5,4276,27,17,...,4,2,3,18,2,No,Low,Senior,No Promotion 5+ Years,Normal
9996,9997,35,Female,Divorced,Marketing,Executive,3,10327,60,19,...,4,3,4,31,1,No,Medium,Senior,No Promotion 5+ Years,Normal
9997,9998,23,Male,Divorced,IT,Manager,3,12592,68,10,...,4,4,2,12,1,Yes,Medium,Senior,No Promotion 5+ Years,Normal
9998,9999,42,Female,Single,Marketing,Manager,3,9287,26,18,...,3,2,2,18,3,No,Medium,Senior,No Promotion 5+ Years,Normal
9999,10000,39,Female,Divorced,Finance,Executive,2,7225,54,16,...,4,1,1,6,2,Yes,Medium,Senior,No Promotion 5+ Years,Normal

In [22]:
# -------------------------------
# STEP 7: SAVE CLEAN DATA
# -------------------------------

# Save final cleaned dataset to new CSV file
df.to_csv("D:/1.My Projects for DS/Data Engineer Role/clean_employee_data.csv", index=False)

print("Clean Data Saved Successfully ✅")

Clean Data Saved Successfully ✅

### SQL connection

In [24]:
# First method to load data in sql But slow
# import mysql.connector
# conn = mysql.connector.connect(
 #    host ="localhost",
 #    user="root",
 #    password = "4993",
 #    database = "hr_analytics_Data_engineer"
# )
# cursor = conn.cursor()
# print("connected to MySQL")*/

In [25]:
# Loop through each row of the DataFrame
# for i, row in df.iterrows():
    
    # Execute SQL INSERT query for each row
#    cursor.execute("""
#        INSERT INTO employee_data 
#        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
#    """, tuple(row))
    
    # tuple(row) converts the row data into tuple format
    # Example: (1, 58, 'Male', 'Finance', ...)


# Save all inserted data permanently into database
# conn.commit()

# Close the database connection
# conn.close()

# Print success message
# print("Data Loaded Successfully 🚀")

In [26]:
#### Second methos for load data in SQL it so fast

from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:4993@localhost/hr_analytics_Data_engineer")

df.to_sql(
    name='employee_data',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=1000
)

print("Data Loaded Successfully 🚀")

Data Loaded Successfully 🚀

In [27]:
df

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition,Income_Category,Experience_Level,Promotion_Status,Risk_Flag
0,1,58,Male,Single,Finance,Manager,5,7332,81,24,...,4,1,1,49,3,No,Medium,Senior,No Promotion 5+ Years,Normal
1,2,48,Female,Divorced,HR,Assistant,4,6069,55,18,...,4,1,1,25,1,No,Medium,Senior,No Promotion 5+ Years,Normal
2,3,34,Female,Married,Marketing,Manager,4,11485,65,6,...,1,4,3,21,1,Yes,Medium,Mid,No Promotion 5+ Years,High Risk
3,4,27,Female,Divorced,HR,Manager,4,18707,28,12,...,3,4,1,46,2,No,High,Senior,No Promotion 5+ Years,Normal
4,5,40,Male,Married,HR,Analyst,1,16398,92,3,...,1,1,1,43,4,No,High,Mid,Recently Promoted,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,22,Female,Divorced,Marketing,Manager,5,4276,27,17,...,4,2,3,18,2,No,Low,Senior,No Promotion 5+ Years,Normal
9996,9997,35,Female,Divorced,Marketing,Executive,3,10327,60,19,...,4,3,4,31,1,No,Medium,Senior,No Promotion 5+ Years,Normal
9997,9998,23,Male,Divorced,IT,Manager,3,12592,68,10,...,4,4,2,12,1,Yes,Medium,Senior,No Promotion 5+ Years,Normal
9998,9999,42,Female,Single,Marketing,Manager,3,9287,26,18,...,3,2,2,18,3,No,Medium,Senior,No Promotion 5+ Years,Normal
9999,10000,39,Female,Divorced,Finance,Executive,2,7225,54,16,...,4,1,1,6,2,Yes,Medium,Senior,No Promotion 5+ Years,Normal

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Employee_ID                    10000 non-null  int64
 1   Age                            10000 non-null  int32
 2   Gender                         10000 non-null  object
 3   Marital_Status                 10000 non-null  object
 4   Department                     10000 non-null  object
 5   Job_Role                       10000 non-null  object
 6   Job_Level                      10000 non-null  int64
 7   Monthly_Income                 10000 non-null  int32
 8   Hourly_Rate                    10000 non-null  int64
 9   Years_at_Company               10000 non-null  int64
 10  Years_in_Current_Role          10000 non-null  int64
 11  Years_Since_Last_Promotion     10000 non-null  int64
 12  Work_Life_Balance              10000 non-null  int64
 13  Job_Satisfaction               10000 non-null  int64
 14  Performance_Rating             10000 non-null  int64
 15  Training_Hours_Last_Year       10000 non-null  int64
 16  Overtime                       10000 non-null  object
 17  Project_Count                  10000 non-null  int64
 18  Average_Hours_Worked_Per_Week  10000 non-null  int64
 19  Absenteeism                    10000 non-null  int64
 20  Work_Environment_Satisfaction  10000 non-null  int64
 21  Relationship_with_Manager      10000 non-null  int64
 22  Job_Involvement                10000 non-null  int64
 23  Distance_From_Home             10000 non-null  int64
 24  Number_of_Companies_Worked     10000 non-null  int64
 25  Attrition                      10000 non-null  object
 26  Income_Category                10000 non-null  object
 27  Experience_Level               10000 non-null  object
 28  Promotion_Status               10000 non-null  object
 29  Risk_Flag                      10000 non-null  object
dtypes: int32(2), int64(18), object(10)
memory usage: 2.2+ MB